%分析任务点的本身价格,周围任务总价格、任务密集度，会员密集度，会员信誉度与任务完成情况关系
clear all
pathWriteMat='E:\ana\mat\';%记录计算数据文件路径
%%
token='m1';                                                 %读取已结束项目任务数据文件
loadfilename=strcat(strcat(pathWriteMat,token),'.mat');
load(loadfilename,'compl_Mission_lat_lon','compl_Mission_price','compl_Mission','compl_Mission_ID');
%%
%   stCompl_Mission_Price			任务价格
%选择5人，22人，60人统计
% 	stCount_Member_MisSum			定会员数的任务总数
% 	stCount_Member_DisMean			定会员数的会员平均距离		stCount_Member_DisStd
% 	stCount_Member_CreMean      	定会员数的平均信誉值 2	 stCount_Member_CreStd
%选择2个任务，5个任务，10个任务
% 	stCount_Mission_DisMean     	定任务数的任务平均距离		stCount_Mission_DisStd 
% 	stCount_Mission_PriMean     	定任务数的任务平均价格		stCount_Mission_PriStd
%选择2公里，5公里，50公里
% 	stDis_Member_Count          	定距离的会员总数 3			
% 	stDis_Member_CreMean        	定距离的平均会员信誉值 4	stDis_Member_CreStd
% 	stDis_Member_DisMean        	定距离的会员平均距离		 stDis_Member_DisStd
% 	stDis_Member_MisSum         	定距离的会员所拥有的任务总数
% 	stDis_Mission_Count         	定距离的任务总数
% 	stDis_Mission_PriMean       	定距离的任务平均价格		stDis_Mission_PriStd  
% 	stDis_Mission_DisMean       	定距离的任务平均距离		stDis_Mission_DisStd 
% 	stKer_Mission_Distance 			任务聚类中心距任务距离
% 	stMemberKer_Mission_Distance	会员中心与各任务的最小距离
% 	stKer_Member_Distance 			会员到其会员中心的距离
token='stand_Data';                                     %读取标准化的分析用数据文件
savefilename=strcat(strcat(pathWriteMat,token),'.mat');
load(savefilename,'stCompl_Mission_Price','stCount_Member_MisSum','stCount_Member_DisMean','stCount_Member_DisStd',...
	'stCount_Member_CreMean','stCount_Member_CreStd','stCount_Mission_DisMean','stCount_Mission_DisStd',...
	'stCount_Mission_PriMean','stCount_Mission_PriStd','stDis_Member_Count','stDis_Member_CreSum','stDis_Member_CreMean','stDis_Member_CreStd',...
	'stDis_Member_DisSum','stDis_Member_DisMean','stDis_Member_DisStd','stDis_Member_MisSum','stDis_Mission_Count',...
	'stDis_Mission_PriSum','stDis_Mission_PriMean','stDis_Mission_PriStd','stDis_Mission_DisSum','stDis_Mission_DisMean','stDis_Mission_DisStd',...
	'stKer_Mission_Distance','stMemberKer_Mission_Distance','stKer_Member_Distance');
%%
% %NaN数据处理，由于定距离统计时在一定距离内存在无会员和无任务可能,因此区分为allNoNaN_Data，other_Data分别处理。
% data=[compl_Mission,stCompl_Mission_Price,stCount_Member_MisSum,stCount_Member_DisMean,stCount_Member_DisStd,...
% 	stCount_Member_CreMean,stCount_Member_CreStd,stCount_Mission_DisMean,stCount_Mission_DisStd,...
% 	stCount_Mission_PriMean,stCount_Mission_PriStd,stDis_Member_Count,stDis_Member_CreSum,stDis_Member_CreMean,stDis_Member_CreStd,...
% 	stDis_Member_DisSum,stDis_Member_DisMean,stDis_Member_DisStd,stDis_Member_MisSum,stDis_Mission_Count,...
% 	stDis_Mission_PriSum,stDis_Mission_PriMean,stDis_Mission_PriStd,stDis_Mission_DisSum,stDis_Mission_DisMean,stDis_Mission_DisStd,...
% 	stKer_Mission_Distance,stMemberKer_Mission_Distance];
% name_Data1={'stCompl_Mission_Price','stCount_Member_MisSum1','stCount_Member_MisSum2','stCount_Member_MisSum3',...
%     'stCount_Member_DisMean1','stCount_Member_DisMean2','stCount_Member_DisMean3',...
%     'stCount_Member_DisStd1','stCount_Member_DisStd2','stCount_Member_DisStd3',...
% 	'stCount_Member_CreMean1','stCount_Member_CreMean2','stCount_Member_CreMean3',...
%     'stCount_Member_CreStd1','stCount_Member_CreStd2','stCount_Member_CreStd3',...
%     'stCount_Mission_DisMean1','stCount_Mission_DisMean2','stCount_Mission_DisMean3',...
%     'stCount_Mission_DisStd1','stCount_Mission_DisStd2','stCount_Mission_DisStd3',...
% 	'stCount_Mission_PriMean1','stCount_Mission_PriMean2','stCount_Mission_PriMean3',...
%     'stCount_Mission_PriStd1','stCount_Mission_PriStd2','stCount_Mission_PriStd3',...
%     'stDis_Member_Count1','stDis_Member_Count2','stDis_Member_Count3',...
%     'stDis_Member_CreSum1','stDis_Member_CreSum2','stDis_Member_CreSum3',...
%     'stDis_Member_CreMean1','stDis_Member_CreMean2','stDis_Member_CreMean3',...
%     'stDis_Member_CreStd1','stDis_Member_CreStd2','stDis_Member_CreStd3',...
% 	'stDis_Member_DisSum1','stDis_Member_DisSum2','stDis_Member_DisSum3',...
%     'stDis_Member_DisMean1','stDis_Member_DisMean2','stDis_Member_DisMean3',...
%     'stDis_Member_DisStd1','stDis_Member_DisStd2','stDis_Member_DisStd3',...
%     'stDis_Member_MisSum1','stDis_Member_MisSum2','stDis_Member_MisSum3',...
%     'stDis_Mission_Count1','stDis_Mission_Count2','stDis_Mission_Count3',...
% 	'stDis_Mission_PriSum1','stDis_Mission_PriSum2','stDis_Mission_PriSum3',...
%     'stDis_Mission_PriMean1','stDis_Mission_PriMean2','stDis_Mission_PriMean3',...
%     'stDis_Mission_PriStd1','stDis_Mission_PriStd2','stDis_Mission_PriStd3',...
%     'stDis_Mission_DisSum1','stDis_Mission_DisSum2','stDis_Mission_DisSum3',...
%     'stDis_Mission_DisMean1','stDis_Mission_DisMean2','stDis_Mission_DisMean3',...
%     'stDis_Mission_DisStd1','stDis_Mission_DisStd2','stDis_Mission_DisStd3',...
% 	'stKer_Mission_Distance','stMemberKer_Mission_Distance'};
% data_noNaN=[compl_Mission,stCompl_Mission_Price,stCount_Member_MisSum,stCount_Member_DisMean,stCount_Member_DisStd,...
% 	stCount_Member_CreMean,stCount_Member_CreStd,stCount_Mission_DisMean,stCount_Mission_DisStd,...
% 	stCount_Mission_PriMean,stCount_Mission_PriStd,stDis_Member_Count,stDis_Member_CreSum,stDis_Member_CreMean(:,3),stDis_Member_CreStd(:,3),...
% 	stDis_Member_DisSum,stDis_Member_DisMean(:,3),stDis_Member_DisStd(:,3),stDis_Member_MisSum,stDis_Mission_Count,...
% 	stDis_Mission_PriSum,stDis_Mission_PriMean(:,3),stDis_Mission_PriStd(:,3),stDis_Mission_DisSum,stDis_Mission_DisMean(:,3),stDis_Mission_DisStd(:,3),...
% 	stKer_Mission_Distance,stMemberKer_Mission_Distance];
% name_Data2={'stCompl_Mission_Price','stCount_Member_MisSum1','stCount_Member_MisSum2','stCount_Member_MisSum3',...
%     'stCount_Member_DisMean1','stCount_Member_DisMean2','stCount_Member_DisMean3',...
%     'stCount_Member_DisStd1','stCount_Member_DisStd2','stCount_Member_DisStd3',...
% 	'stCount_Member_CreMean1','stCount_Member_CreMean2','stCount_Member_CreMean3',...
%     'stCount_Member_CreStd1','stCount_Member_CreStd2','stCount_Member_CreStd3',...
%     'stCount_Mission_DisMean1','stCount_Mission_DisMean2','stCount_Mission_DisMean3',...
%     'stCount_Mission_DisStd1','stCount_Mission_DisStd2','stCount_Mission_DisStd3',...
% 	'stCount_Mission_PriMean1','stCount_Mission_PriMean2','stCount_Mission_PriMean3',...
%     'stCount_Mission_PriStd1','stCount_Mission_PriStd2','stCount_Mission_PriStd3',...
%     'stDis_Member_Count1','stDis_Member_Count2','stDis_Member_Count3',...
%     'stDis_Member_CreSum1','stDis_Member_CreSum2','stDis_Member_CreSum3',...
%     'stDis_Member_CreMean3',...
%     'stDis_Member_CreStd3',...
% 	'stDis_Member_DisSum1','stDis_Member_DisSum2','stDis_Member_DisSum3',...
%     'stDis_Member_DisMean3',...
%     'stDis_Member_DisStd3',...
%     'stDis_Member_MisSum1','stDis_Member_MisSum2','stDis_Member_MisSum3',...
%     'stDis_Mission_Count1','stDis_Mission_Count2','stDis_Mission_Count3',...
% 	'stDis_Mission_PriSum1','stDis_Mission_PriSum2','stDis_Mission_PriSum3',...
%     'stDis_Mission_PriMean3',...
%     'stDis_Mission_PriStd3',...
%     'stDis_Mission_DisSum1','stDis_Mission_DisSum2','stDis_Mission_DisSum3',...
%     'stDis_Mission_DisMean3',...
%     'stDis_Mission_DisStd3',...
% 	'stKer_Mission_Distance','stMemberKer_Mission_Distance'};
% log_NoNData=sum(isnan(data),2)>0;
% allNoNaN_Data=data(~log_NoNData,:);
% other_Data=data_noNaN(log_NoNData,:);
% %allNoNaNCompl_Prob=tabulate(allNoNaN_Data(:,1));    %总体完成度61.5%   530个任务
% %otherCompl_Prob=tabulate(other_Data(:,1));          %总体完成度64.3%   205个任务
% %%
% %应用logit回归法建模
% % x_data1=allNoNaN_Data(:,2:end);
% % y_data1=allNoNaN_Data(:,1);
% % [prob_y1,prob_YValue1,b1,dev1,stats1]=logit_ansys(x_data1,y_data1);%预测符合率86.42.02%,530;
% % log_Remove=stats1.residd<2.5;       %消除个别奇异点
% % x_data2=x_data1(log_Remove,:);
% % y_data2=y_data1(log_Remove,:);
% % [prob_y2,prob_YValue2,b2,dev2,stats2]=logit_ansys(x_data2,y_data2); %预测符合率95.02%,502;
% x_data3=other_Data(:,2:end);
% y_data3=other_Data(:,1);
% [prob_y3,prob_YValue3,b3,dev3,stats3]=logit_ansys(x_data3,y_data3);%预测符合率85.25%,305;
% % log_Remove3=stats3.residd<2.5;       %消除个别奇异点
% % x_data4=x_data3(log_Remove3,:);
% % y_data4=y_data3(log_Remove3,:);
% % [prob_y4,prob_YValue4,b4,dev4,stats4]=logit_ansys(x_data4,y_data4); %预测符合率96.58%,292;
% %逐步去除最大p值因素
% %[valueName,prob_y,prob_YValue,b,dev,stats]=logit_ansysNum(x_data3,y_data3,name_Data2);
% % %绘制logit标准化离差残差图
% % scrsz = get(0,'ScreenSize');
% % hF1=figure('Position',[scrsz(3)/8 scrsz(4)/15 scrsz(3)*4/5 scrsz(4)*4/5]);
% % set(hF1,'Name','logit标准化残差图','Colormap',spring);
% % scatter(1:length(stats.residd),stats.residd,50,'+');
%%
% %所有任务总成败率
% compl_Prob=tabulate(compl_Mission);  %总体完成度62.52%   835个任务
% %整个大区的原始价格数据按65-70、70-75、75、80、85分为5个大区重新归类；
% filter_85=(compl_Mission_price<70)*65+(compl_Mission_price<75&compl_Mission_price>=70)*70+(compl_Mission_price==75)*75+(compl_Mission_price==80)*80+(compl_Mission_price==85)*85;
% anRelat_Data=[compl_Mission,filter_85,stCompl_Mission_Price,stKer_Mission_Distance,stDis_Member_CreSum(:,2)];
% anRelat_65=anRelat_Data(anRelat_Data(:,2)==65,:);anFreq_65=tabulate(anRelat_65(:,1));   % 完成度54.12% 510个任务
% anRelat_70=anRelat_Data(anRelat_Data(:,2)==70,:);anFreq_70=tabulate(anRelat_70(:,1));   % 完成度74.4%  207个任务
% anRelat_75=anRelat_Data(anRelat_Data(:,2)==75,:);anFreq_75=tabulate(anRelat_75(:,1));   % 完成度75.65% 78个任务
% anRelat_80=anRelat_Data(anRelat_Data(:,2)==80,:);anFreq_80=tabulate(anRelat_80(:,1));   % 完成度69.23% 13个任务
% anRelat_85=anRelat_Data(anRelat_Data(:,2)==85,:);anFreq_85=tabulate(anRelat_85(:,1));   % 完成度88.89% 27个任务
% anFreq_price=[anFreq_65(2,2:3);anFreq_70(2,2:3);anFreq_75(2,2:3);anFreq_80(2,2:3);anFreq_85(2,2:3)];
% anFreq_price=[[65,70,75,80,85]',anFreq_price];
% scrsz = get(0,'ScreenSize');
% hF1=figure('Position',[scrsz(3)/8 scrsz(4)/15 scrsz(3)*4/5 scrsz(4)*4/5]);
% set(hF1,'Name','任务价格-完成情况图','Colormap',cool);
% scatter(anFreq_price(:,3),anFreq_price(:,2),12,anFreq_price(:,1),'full','o')
%%
% %因素相关性分析。按任务距会员中心的距离从远到近，每25个任务1组，计算每组的成功概率。通过分析各组相应因素的平均值的相关性分析，确定主要影响因素。
% %成败概率矩阵准备
% anRelat_Data=[compl_Mission,stCompl_Mission_Price,stCount_Member_MisSum(:,2),stCount_Member_DisMean(:,2),stCount_Member_DisStd(:,2),...
% 	stCount_Member_CreMean(:,2),stCount_Member_CreStd(:,2),stCount_Mission_DisMean(:,2),stCount_Mission_DisStd(:,2),...
% 	stCount_Mission_PriMean(:,2),stCount_Mission_PriStd(:,2),stDis_Member_Count(:,2),stDis_Member_CreSum(:,2),stDis_Member_CreMean(:,2),stDis_Member_CreStd(:,2),...
% 	stDis_Member_DisSum(:,2),stDis_Member_DisMean(:,2),stDis_Member_DisStd(:,2),stDis_Member_MisSum(:,2),stDis_Mission_Count(:,2),...
% 	stDis_Mission_PriSum(:,2),stDis_Mission_PriMean(:,2),stDis_Mission_PriStd(:,2),stDis_Mission_DisSum(:,2),stDis_Mission_DisMean(:,2),stDis_Mission_DisStd(:,2),...
% 	stKer_Mission_Distance,stMemberKer_Mission_Distance];
% count=25;
% anRelat_Prob=condProb(anRelat_Data,count);
% [n,m]=size(anRelat_Prob);
% result_relat=corrcoef(anRelat_Prob);
% scrsz = get(0,'ScreenSize');
% hF1=figure('Position',[scrsz(3)/8 scrsz(4)/15 scrsz(3)*4/5 scrsz(4)*4/5]);
% set(hF1,'Name','成败因素相关性图','Colormap',cool);
% gplotmatrix(result_relat(:,1:5),(1:28)',[],'rgbymc','o*+^<>',2); 
% %相关系数排序
% %6stCount_Member_CreMean(:,2)、（7stCount_Member_CreStd(:,2)、20stDis_Mission_Count(:,2)、28stMemberKer_Mission_Distance、21stDis_Mission_PriSum(:,2)）
%%
% %按任务距会员中心的距离从远到近。每22个任务1组，计算每组的成功概率。通过分析各组成功概率与其它因素的成败概率因素图，确定影响任务成败的因素及影响方式。
% %成败概率矩阵准备
% % anRelat_Data=[compl_Mission,stCompl_Mission_Price,stDis_Mission_Count(:,3),stDis_Member_CreSum(:,3),stCount_Member_CreMean(:,3),stDis_Member_MisSum(:,2),...
% %   stCount_Member_DisMean(:,3),stDis_Member_Count(:,3),stCount_Mission_DisMean(:,1),stMemberKer_Mission_Distance];%直觉选取
% anRelat_Data=[compl_Mission,stCompl_Mission_Price,stDis_Mission_PriSum(:,2),stDis_Mission_Count(:,2),stDis_Member_Count(:,2),...
%               stDis_Member_MisSum(:,2),stCount_Member_CreMean(:,2),stMemberKer_Mission_Distance]; %参考相关系数分析结果
% name={'compl_Mission';'stCompl_Mission_Price';'stDis_Mission_PriSum(:,2)';'stDis_Mission_Count(:,2)';'stDis_Member_Count(:,2)';...
%       'stDis_Member_MisSum(:,2)';'stCount_Member_CreMean(:,2)';'stMemberKer_Mission_Distance'};
% [anRelat_Prob,g]=condProb(anRelat_Data,22);
% [n,m]=size(anRelat_Prob);
% %观察数据变化规律
% scrsz = get(0,'ScreenSize');
% hF1=figure('Position',[scrsz(3)/8 scrsz(4)/15 scrsz(3)*4/5 scrsz(4)*4/5]);
% set(hF1,'Name','成败概率因素图','Colormap',cool);
% gplotmatrix(anRelat_Prob(:,2:m),anRelat_Prob(:,1),anRelat_Prob(:,m),'rgbymc','oooooo******++++++^^^^^^<<<<<<>>>>>>XX',8);             %绘制散点矩阵图观察各因素对成败概率的影响
% ylabel(name(2:end));
% %scatter3(anRelat_Prob(:,2),anRelat_Prob(:,4),anRelat_Prob(:,5),6,anRelat_Prob(:,1),'full','o')
% %结论:任务未完成的原因主要是任务间竞争关系强、任务定价过低的影响。
% %     整个任务付出对任务完成作用均衡，未表现出距离远的任务完成难度过大的特征。
% %     任务价格对任务完成起正激励作用，任务价格越高任务完成越好。
% %     任务间竞争关系越高，任务完成越差。
%%
% 神经网络分析
data_noNaN=[compl_Mission,stCompl_Mission_Price,stCount_Member_MisSum,stCount_Member_DisMean,stCount_Member_DisStd,...
	stCount_Member_CreMean,stCount_Member_CreStd,stCount_Mission_DisMean,stCount_Mission_DisStd,...
	stCount_Mission_PriMean,stCount_Mission_PriStd,stDis_Member_Count,stDis_Member_CreSum,stDis_Member_CreMean(:,3),stDis_Member_CreStd(:,3),...
	stDis_Member_DisSum,stDis_Member_DisMean(:,3),stDis_Member_DisStd(:,3),stDis_Member_MisSum,stDis_Mission_Count,...
	stDis_Mission_PriSum,stDis_Mission_PriMean(:,3),stDis_Mission_PriStd(:,3),stDis_Mission_DisSum,stDis_Mission_DisMean(:,3),stDis_Mission_DisStd(:,3),...
	stKer_Mission_Distance,stMemberKer_Mission_Distance];
x1=data_noNaN(:,2:end);
y1=data_noNaN(:,1);
x=x1';
y=y1';
y=full(ind2vec(y+1));